### ISSUE TITLE
Asegurarse que esten los campos necesarios para registrarse

### ISSUE THREAD

**Issue by Trixtaro** [Trixtaro/rutasturisticas#37]
En **RegisterTurista** solo están algunos campos, faltan por ejemplo los siguientes:

- Cédula
- Pasaporte
- Fecha de nacimiento
- Apellido paterno y materno por separado
- Usuario, contraseña y los datos necesarios del usuario

También evitar el uso excesivo de etiquetas **div** que complejizan la visualizacion del componente.

Revisar los cambios que se han hecho.

Aceptar el pull request antes de realizar este issue

**Comment by DJLuis97** [comment]
Como aplico bien el CSS sin esos **div**

**Comment by Trixtaro** [comment]
Aplicas todas las clases en un solo div

**Comment by Trixtaro** [comment]
Ya pude hacer q se registren con react
